name: Security Scan

on:
  push:
    branches: [ "main" ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/upload-artifact@v3.1.3

      - name: Run Syhunt Code (SAST)
        run: |
          docker run --rm -v ${{ github.workspace }}:/code syhunt/syhunt-code scan /code --report report.html

      - name: Upload Report
        uses: actions/upload-artifact@v3
        with:
          name: security-report
          path: report.html
