name: Security Scan CI

on:
  push:
    branches: [ "main" ]

jobs:
  sast_semgrep:
    name: Código Seguro com Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar e rodar Semgrep manualmente
        run: |
          pip install semgrep
          semgrep scan --config auto --json > semgrep-report.json

      - name: Upload do relatório do Semgrep
        uses: actions/upload-artifact@v3.1.2
        with:
          name: semgrep-report
          path: semgrep-report.json

  dast_zap:
    name: OWASP ZAP DAST
    runs-on: ubuntu-latest
    needs: sast_semgrep

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Start da API (Spring Boot)
        run: |
          nohup ./mvnw spring-boot:run &
          sleep 20

      - name: Rodar ZAP Baseline Scan
        run: |
          docker run -v ${{ github.workspace }}:/zap/wrk/:rw \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:808

      - name: Upload do relatório do ZAP
        uses: actions/upload-artifact@v3.1.2
        with:
          name: zap-report
          path: zap-report.html
