name: Security Scan CI

on:
  push:
    branches: [ "main" ]

jobs:
  sast_semgrep:
    name: Código Seguro com Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  # Updated from v3 to v4

      - name: Rodar análise com Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"

  dast_zap:
    name: OWASP ZAP DAST
    runs-on: ubuntu-latest
    needs: sast_semgrep

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4  # Updated from v3 to v4

      - name: Start da API (Spring Boot)
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          nohup ./mvnw spring-boot:run &
          sleep 20

      - name: Rodar ZAP Baseline Scan
        run: |
          docker run -v ${{ github.workspace }}:/zap/wrk/:rw \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8081 \
            -r zap-report.html

      - name: Upload do relatório do ZAP
        uses: actions/upload-artifact@v4  # Updated from v3 to v4
        with:
          name: zap-report
          path: zap-report.html
