name: Security Scan CI

on:
  push:
    branches: [ "main" ]

jobs:
  sast_semgrep:
    name: Código Seguro com Semgrep
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Rodar análise com Semgrep
        uses: returntocorp/semgrep-action@v1
        with:
          config: "auto"

  dast_zap:
    name: OWASP ZAP DAST
    runs-on: ubuntu-latest
    needs: sast_semgrep

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Generate Maven Wrapper
        run: |
          mvn -N io.takari:maven:wrapper -Dmaven=3.8.6
          chmod +x mvnw

      - name: Build application
        run: |
          ./mvnw clean package -DskipTests

      - name: Start da API (Spring Boot)
        env:
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: |
          java -jar target/*.jar &
          sleep 10
          until curl -s http://localhost:8080/actuator/health; do
            sleep 5
          done

      - name: Pull ZAP Docker Image
        run: docker pull ghcr.io/zaproxy/zaproxy:stable

      - name: Rodar ZAP Baseline Scan
        run: |
          docker run -v ${{ github.workspace }}:/zap/wrk/:rw \
            ghcr.io/zaproxy/zaproxy:stable zap-baseline.py \
            -t http://host.docker.internal:8080 \
            -r zap-report.html \
            -m 10

      - name: Upload do relatório do ZAP
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-report.html
          retention-days: 3
